# development overrides for compose.yml
services:
  bot:
    build: .
    environment:
      ENVIRONMENT: dev

  api:
    build: .
    environment:
      ENVIRONMENT: dev

secrets:
  env:
    file: .env.docker
  github_private_key:
    file: secrets/github__private_key
