# development overrides for compose.yml
services:
  bot:
    build: .
    environment:
      ENVIRONMENT: dev
      API_ROOT_PATH:
      HEALTH_CHECK_URL: http://localhost:7100/health
    develop:
      watch:
        - action: sync
          path: bot/src/ghutils/cogs
          target: /app/bot/src/ghutils/cogs

secrets:
  env:
    file: .env.docker
  github_private_key:
    file: secrets/github__private_key
