# production overrides for compose.yml
services:
  bot:
    restart: unless-stopped
    image: "${IMAGE}"
    environment:
      ENVIRONMENT: prod
      API_ROOT_PATH: /api

  postgres:
    restart: unless-stopped

secrets:
  env:
    file: .env
  github_private_key:
    file: github__private_key
