# production overrides for compose.yml
services:
  bot:
    restart: unless-stopped
    image: "ghcr.io/object-object/discord-github-utils@${IMAGE_ID}"
    environment:
      ENVIRONMENT: prod

  postgres:
    restart: unless-stopped

secrets:
  env:
    file: .env
  github_private_key:
    file: github__private_key
