# production overrides for compose.yml
services:
  bot:
    restart: unless-stopped
    image: "${IMAGE}"
    environment:
      ENVIRONMENT: prod
      API_ROOT_PATH: /api
      GITHUB__APP_ID: '997788'
      GITHUB__CLIENT_ID: Iv23li0slKG6vf9kOBef
      GITHUB__REDIRECT_URI: https://ghutils.object.gay/api/login
      GITHUB__DEFAULT_INSTALLATION_ID: '54847303'
      HEALTH_CHECK_URL: https://ghutils.object.gay/api/health

  postgres:
    restart: unless-stopped

secrets:
  env:
    file: .env
  github_private_key:
    file: secrets/github__private_key
